### PR TITLE
Fix browser build

### LINKED ISSUE #31: es6 import not working
After developing #30 i stumbled across an issue, where I was not able to use the es6 `import` syntax, to import this module in a  non ejected`create-react-app` setup.

`create-react-app` before ejecting it has its own magical webpack setup, and upon digging abit I found a post on the webpack tracker that talked about multiple builds in npm module package file, and how webpack by default uses the `browser` key.

Upon inspecting our setup i saw the `lib/standalone.js` was the one stored on the browser key, when i tried to import this module the following error happens:

skaermbillede 2018-03-23 kl 21 49 53

I tried to swap the `standalone.js` with the `bundle.js` and then everything works, I think there is a bug with the way `standalone.js` exports this module to the browsers.

I did find this post also on the webpack issue tracker, https://github.com/webpack/webpack/issues/1979 suggesting how you can order `mainFields` in your webpack resolver, but I haven't tested this or if this is remotly related to this case here.

### PR DESCRIPTION
**Pull request by egeriis**
This fixes #31

### CODE REVIEW

**Comment by akkie** [comment]
@egeriis It would be great if this could be published with a new version.

**Comment by egeriis** [comment]
@akkie Thank you, forgot that.

**Comment by egeriis** [comment]
Published as 1.4.1

**Comment by akkie** [comment]
@egeriis Thanks! The import works now, expect that Flow.js or Eslint cannot find the module.

```
$ flow check
Error -------------------------------------------------------------------------------------- 
Cannot resolve module `zipcelx`.

   4| import zipcelx from 'zipcelx';
                          ^^^^^^^^^

```

```
$ eslint --ext .js,.jsx src/ test/
  4:21  error  Unable to resolve path to module 'zipcelx'  import/no-unresolved
  4:21  error  Missing file extension for "zipcelx"        import/extensions

✖ 2 problems (2 errors, 0 warnings)

```

**Comment by egeriis** [comment]
Uhm. Why does that happen... 🤔 I wonder if flow and eslint doesn't understand if there are no `main` entry in `package.json`.

**Comment by egeriis** [comment]
@akkie Is your eslint env set to "browser"? 🙂

**Comment by akkie** [comment]
@egeriis Yes, it's set to `"browser" : true`. It seems that both tools need the main entry in the package.json. If I manually add the entry `"main": "lib/module.js",` in the package.json of the `zipcelx` module located in my node_modules directory, then I have no errors anymore.

**Comment by akkie** [comment]
@egeriis Thanks :+1:  Now, it works as expected.

**Pull request merged**
