### PR TITLE
Add an second sheet for explanation

### PR DESCRIPTION
**Pull request by esmee-peters**

### CODE REVIEW

**Comment by egeriis** [comment]
@esmee-peters Closed due to irrelevance, or? 🙂

**Comment by esmee-peters** [comment]
@egeriis Sorry, didn't set the settings while pushing to or fork repro. So it created the PR here and not in or separete repro. You can close/remove it.

Other question; I'm currently working on a new feature to create mutiple tabs in our forked repro. If you like that, I can make a new PR with this feature?

**Comment by egeriis** [comment]
@esmee-peters We're very open to ideas for improvements. We want to maintain our mantra of having a minimal bundle size though, as that's our edge towards alternative libs 🙂 

I could imagine that you would need to modify the static XML files we include for this to work, so it would increase the bundle size significantly?

**Comment by esmee-peters** [comment]
@egeriis I have merged the feature of multiple sheets in our forked repro. You can take a look at it here: https://github.com/DigitPaint/zipcelx/commit/e7f41c9d5c57677cdad4f386ec3663724077cc70

I really understand what your saying about the bundle size, but it only increased with 1KB. If you like the feature I can make a PR in your repro. Let me know :)

**Comment by egeriis** [comment]
@esmee-peters I'd be happy to receive a PR for this 🙂

**Comment by esmee-peters** [comment]
Sure :)

**Pull request closed without merging**
